### ISSUE TITLE
能弄个独立的收款系统？

### ISSUE THREAD

**Issue by xingline** [mhcyong/TeePay#1]
能弄个独立的收款系统？用户能够自定义金额并支付，移动端为主，多少钱？

**Comment by mhcyong** [comment]
我这款是基于Typecho的个人收款插件，弄个收款系统的话就需要重新开发了，不过收款接口的使用都是相同的，你可以借鉴，需求明确的话可以实现的。

**Comment by xingline** [comment]
没有什么大的需要，就一个小的收款系统，跟你这个一样，只不过要金额用户可自己输入，支持微信和支付宝即可。

**Comment by mhcyong** [comment]
如果只有这点需求，使用的又是Typecho的话，我这个插件把金额那块改成输入框即可。
支付宝是使用当面付，每日限额5万，微信使用的payjs.cn，个人身份即可申请。

**Comment by xingline** [comment]
有限额啊？有其他的不限额的支付方式么，个人的

**Comment by mhcyong** [comment]
个人正规渠道都是限额，一般每天5万封顶，如果你超过这个限度还是去注册一个企业吧。
其它不限额的方法也有，去网上搜一大把，不过我不推荐。

**Comment by xingline** [comment]
是啊不靠谱，几万的限额不够看，谢谢了
