### ISSUE TITLE
启用插件出现数据库错误

### ISSUE THREAD

**Issue by FFFcat** [mhcyong/TeePay#10]
![image](https://user-images.githubusercontent.com/41832582/71305510-53aaca80-2410-11ea-9d23-26353ad7842a.png)
数据库用的是sqlite3

**Comment by mhcyong** [comment]
不好意思，插件不支持sqlite数据库，使用的是mysql数据库。

**Comment by FFFcat** [comment]
好的，谢谢

**Comment by FFFcat** [comment]
那菜单栏的付费栏怎么弄掉？看了[issue2](https://github.com/mhcyong/TePay/issues/2)，是说禁用插件。。但我都启用不了
![image](https://user-images.githubusercontent.com/41832582/71305627-bea8d100-2411-11ea-8b24-a87ac4191625.png)

**Comment by mhcyong** [comment]
启用的时候应该是相关设置生效了，所以出现了这个菜单栏，去数据库看看怎么去掉这个菜单吧。
