### ISSUE TITLE
存在Cookies-Based XSS攻击

### ISSUE THREAD

**Issue by matchch** [mhcyong/TeePay#12]
级别: 低危
由于是低危就不多写了，利用难度也挺大的，需要能控制Cookies。
Cookies-Base一般是利用同源攻击，也得要求拿下主站才行。

Payload: TeePayCookie=xxxxxxx"/><script>alert("XSS")</script>"
原因: 直接输出cookies 
文件: Plugin.php 中 <?php echo  $TeePayCookie ?>

**Comment by mhcyong** [comment]
你好，非常感谢，已去掉Plugin.php相关代码。

**Comment by matchch** [comment]
感谢修复
