### ISSUE TITLE
兄弟你继续删，分析已经写好了

### ISSUE THREAD

**Issue by matchch** [mhcyong/TeePay#15]
https://www.shinenet.cn/archives/117.html

**Comment by mhcyong** [comment]
欢迎你写，欢迎发到各网站论坛，告诉使用此版本都用户注意，谢谢。

**Comment by mhcyong** [comment]
不好意思，误会你了，我以为你是那个恶意攻击使用者，一天刷单几万的人，看了你博客发现不是你。

**Comment by matchch** [comment]
> 不好意思，误会你了，我以为你是那个恶意攻击使用者，一天刷单几万的人，看了你博客发现不是你。

没事...
