### ISSUE TITLE
为什么我安装插件配置支付宝当面付后，去测试直接弹 服务器错误

### ISSUE THREAD

**Issue by muzikeji** [mhcyong/TeePay#16]
什么原因？![image](https://user-images.githubusercontent.com/52457863/113110306-8198d480-9239-11eb-9c9b-e051387e7e9e.png)

**Comment by mhcyong** [comment]
认真看安装教程，[https://pangsuan.com/p/teepay.html](https://pangsuan.com/p/teepay.html)
