### ISSUE TITLE
支付二维码

### ISSUE THREAD

**Issue by Taylor000** [mhcyong/TeePay#17]
在默认主题下试了，修改二维码接口，然后点击付款 生成的二维码扫出来是 “领取搜狐视频会员”的页面

**Comment by mhcyong** [comment]
> 在默认主题下试了，修改二维码接口，然后点击付款 生成的二维码扫出来是 “领取搜狐视频会员”的页面

生成二维码的接口问题，请参考这篇文章进行修改。
https://pangsuan.com/p/teepay-qrcode-fixed.html  
免费的接口肯定长久不了，所以TePass插件采用服务器本地生成二维码。
