### ISSUE TITLE
卸载插件不干净，菜单栏还在？

### ISSUE THREAD

**Issue by liuzhiping138** [mhcyong/TeePay#2]
卸载插件不干净，菜单栏还在？

**Comment by mhcyong** [comment]
> 卸载插件不干净，菜单栏还在？

旧的版本是存在这个问题，最新版本已经解决了。

**Comment by liuzhiping138** [comment]
更新了，依然存在问题，现在能卸载插件，但是在此安装插件，菜单了出现多个 文章付费 ，没安装一次就会多出一个来。

**Comment by mhcyong** [comment]
安装就增加一个，禁用就减少一个。
