### ISSUE TITLE
添加<?php echo TeePay_Plugin::getTeePay(); ?>后文章无法打开

### ISSUE THREAD

**Issue by aipeach** [mhcyong/TeePay#4]
不管我把<?php echo TeePay_Plugin::getTeePay(); ?>放在post.php文件哪个位置，文章都无法打开。
主题使用的handsome

**Comment by mhcyong** [comment]
你这样让我不知道怎么回答你……

**Comment by aipeach** [comment]
您好，能否告知您的邮件地址呢？我录制了我的操作视频，我发给您看看，因为视频里还有我的IP地址这些所以不方便直接回复

**Comment by mhcyong** [comment]
麻烦你去https://pangsuan.com 上找联系方式，不想在公共地方泄露邮箱，请谅解。

**Comment by aipeach** [comment]
我找到了联系方式，但是您没回复我

**Comment by mhcyong** [comment]
> 我找到了联系方式，但是您没回复我
没有收到你的任何消息，如果你不方便，可以贴错误日志在这里，或者你可以前往 https://pangsuan.com/p/teepay.html 付费获取技术支持。
