### ISSUE TITLE
建议增加记录删除功能

### ISSUE THREAD

**Issue by 64611187** [mhcyong/TeePay#5]
建议增加记录删除功能
还有网站pjax需要回调参数
还有可不可以自定义付费的位置每次的都在文章最后有点不好排版

**Comment by 64611187** [comment]
> 建议增加记录删除功能
> 还有网站pjax需要回调参数
还有可不可以自定义付费的位置每次的都在文章最后有点不好排版

**Comment by mhcyong** [comment]
> 建议增加记录删除功能
> 还有网站pjax需要回调参数
> 还有可不可以自定义付费的位置每次的都在文章最后有点不好排版

记录的删除有打算在后台增加一个子菜单栏实现；
关于位置的问题，可以在文章开头和结尾，中间任意位置不好实现。

**Comment by 64611187** [comment]
> > 建议增加记录删除功能
> > 还有网站pjax需要某些参数
> > 还有可不可以自定义定义的位置每次的都在文章最后有点不好放置
> 
> 记录的删除有打算在后台增加一个子菜单栏实现；
> 关于位置的问题，可以在文章开头和结尾，中间任意位置不好实现。

可以参考这个短代码方式实现的https://www.tongleer.com/1803.html
还有希望添加一个用户可以查看自己的付费记录或者文章

**Comment by mhcyong** [comment]
我这个与那个的思路不一致，不会考虑短代码的方式。
在我的主题是已经实现了查看付费记录，只是没聚合到插件里面。
