### ISSUE TITLE
新版插件不可用

### ISSUE THREAD

**Issue by ghost** [mhcyong/TeePay#7]
在主题post.php文件相应位置添加：`<?php echo TePay_Plugin::getTePay(); ?>`后提示找不到TePay_Plugin，改为Typecho_Widget，页面付费直接消失

**Comment by c939984606** [comment]
<?php echo TePay_Plugin::getTePay(); ?>。

**Comment by c939984606** [comment]
`<?php echo TePay_Plugin::getTePay(); ?>。`

**Comment by ghost** [comment]
不知道是哪里步骤不对？

**Comment by mhcyong** [comment]
> 不知道是哪里步骤不对？

插件肯定可用，操作也很简单，如需协助，请到官网付费购买服务。
