### ISSUE TITLE
handsome主题不显示，后台菜单栏有残留

### ISSUE THREAD

**Issue by Priess0503** [mhcyong/TeePay#8]
你好，我遇到了同样的问题，在主题post.php添加了代码，不显示。同时卸载后菜单栏有残留，添加了标题和付费。但是没有记录！

**Comment by mhcyong** [comment]
关于残留菜单的问题，启用插件就产生菜单，并写进数据库了，禁用就去掉菜单，同时删除数据库中刚生成的菜单，如果你没禁用就删除整个插件，数据库信息还有，菜单当然就保留了。
插件的使用肯定没问题的，演示站点有些就是基础版的，也是在这里下载的，没正常显示很多都是出在配置上。
